# Generated by Django 5.0.2 on 2024-03-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_user", models.PositiveIntegerField(unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone_number", models.CharField(blank=True, default="", max_length=15)),
                ("document", models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "patient",
            },
        ),
    ]
